name: Build and Distribute Flutter macOS App

on:
  push:
    branches:
      - hello

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build macos --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Distribute to Firebase
        run: |
          firebase appdistribution:distribute build/macos/Build/Release/app.app.zip --app ${{ secrets.MAC_APP_ID }} --token ${{ secrets.FIREBASE_TOKEN }} --groups tester