name: Build and Distribute Flutter Windows App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Install msix package
        run: dart pub global activate msix


      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows --release


      - name: Verify Dart and msix installation
        run: |
          dart --version
          dart pub global list
          where dart
          where msix


      - name: Convert .exe to .msix
        run: |
          dart pub global run msix convert `
            --input build/windows/x64/runner/Release/automate_build.exe `
            --output build/msix/automate_build.msix `
            --packageName "automate_build" `
            --version "1.0.0"
        shell: pwsh


      - name: Install App Center CLI
        run: npm install -g appcenter-cli


      - name: Distribute to App Center
        run: |
            appcenter distribute release --app windows_apps/cryodrive_windows --file build/msix/automate_build.msix  --group windows_testers --release-notes "New build with improvements" --token ${{ secrets.APPCENTER_TOKEN }}
        env:
          APPCENTER_TOKEN: ${{ secrets.APPCENTER_TOKEN }}
