name: Build and Distribute Flutter Windows App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows --release

      - name: Install Windows SDK
        run: |
          Invoke-WebRequest -Uri https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/ -OutFile sdk_installer.exe
          Start-Process -Wait -FilePath sdk_installer.exe -Args "/quiet /norestart"

      - name: Convert EXE to MSIX
        run: |
          $packageName = "YourAppName"
          $version = "1.0.0.0"
          $outputDir = "build/msix"
          $exePath = "build/windows/x64/runner/Release/automate_build.exe"
          $msixPath = "$outputDir/${packageName}_${version}.msix"

          # Create output directory if it doesn't exist
          if (-not (Test-Path $outputDir)) {
            New-Item -Path $outputDir -ItemType Directory
          }

          # Path to MakeAppx.exe
          $makeAppxPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\MakeAppx.exe"

          # Use MakeAppx to create MSIX package
          & $makeAppxPath pack /d "build/windows/x64/runner/Release" /p $msixPath /l

      - name: Install App Center CLI
        run: npm install -g appcenter-cli


      - name: Distribute to App Center
        run: |
          appcenter distribute release --app windows_apps/cryodrive_windows --file build/msix/YourAppName_1.0.0.0.msix --group windows_testers --token ${{ secrets.APPCENTER_TOKEN }}
        env:
          APPCENTER_TOKEN: ${{ secrets.APPCENTER_TOKEN }}