name: Build and Distribute Flutter Windows App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows app
        run: flutter build windows --release

      - name: Install MSIX Packaging Tool
        run: |
          choco install microsoft-msix-packaging-tool

      - name: Create MSIX Package
        run: |
          $packageName = "YourAppName" # Change this to your app's name
          $version = "1.0.0.0" # Set your version
          $packageOutputPath = "build/msix/${packageName}_${version}.msix"
        
          # Create the MSIX package
          New-Item -Path "build/msix" -ItemType Directory -Force
          & "$env:ProgramFiles\Windows Kits\10\bin\x64\MakeAppx.exe" pack /d "build/windows/runner/Release" /p $packageOutputPath



